### PR TITLE
Allow adding layers (workaround for #4).

### PR DESCRIPTION
**Pull request by m-mohr**
The separated function addLayer() allows to add layers after the map has been initialized. Allows to work around the issue described in #4.

### CODE REVIEW

**Comment by jbccollins** [comment]
Ok so it looks like your approach is to add an `addLayer` function to the control. My approach was to bind listeners to the layergroup's `layeradd` and `layerremove` events. Tbh I'm not actually sure which is the better approach here. Got any examples of other leaflet controls that do something similar?

**Comment by m-mohr** [comment]
No, I'm not very experienced with Leaflet to be honest.
What I found on the web is that LayerGroup doesn't seem to implement the layeradd/layerremove events. I just tested your fix and it doesn't work for me, unfortunately. I'd prefer your example to work though as it's cleaner. Will investigate further tomorrow. Thanks for all the help so far!

**Comment by jbccollins** [comment]
Ah shoot. You are correct. Hmmm ok I'll fix it.

**Comment by jbccollins** [comment]
Ok 1.0.5 is published. I now listen for the map's `layeradd` event and do a check to make sure that the layer is part of the layer group when deciding if rebinding the tile load events is necessary.

**Comment by m-mohr** [comment]
I'll continue the discussion in #4.

**Pull request closed without merging**
